### ISSUE TITLE
cross version conflict

### ISSUE THREAD

**Issue by swuecho** [com-lihaoyi/geny#37] opened 2022-05-11 01:40 UTC
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/hwu/dev/bestqa_scala/"), "root"):
[error]    com.lihaoyi:geny _3, _2.13
[error] stack trace is suppressed; run last update for the full output
[error] (update) Conflicting cross-version suffixes in: com.lihaoyi:geny
[error] Total time: 2 s, completed May 11, 2022 9:37:55 AM
```

my sbt:

```
val scala3Version = "3.1.2"
val fs2Version = "3.1.0"
val doobieVersion = "1.0.0-RC2"
val circeVersion = "0.14.1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "bestqa_scala",
    version := "0.3.2",
    scalaVersion := scala3Version
  )

// build.sbt
libraryDependencies += "org.scalameta" %% "munit" % "0.7.26" % Test
libraryDependencies += "org.scalameta" %% "munit-scalacheck" % "0.7.26" % Test
libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.15.4" // % Test
testFrameworks += new TestFramework("munit.Framework")

libraryDependencies += "com.softwaremill.sttp.client3" %% "core" % "3.3.4"

libraryDependencies ++= Seq(
  "org.postgresql" % "postgresql" % "42.2.8",
  "io.getquill" %% "quill-jdbc" % "3.16.5-Beta29",
  "io.getquill" %% "quill-doobie" % "3.16.5-Beta29"
)
libraryDependencies += "org.tpolecat" %% "doobie-core" % doobieVersion
libraryDependencies += "org.tpolecat" %% "doobie-postgres" % doobieVersion

libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.25"

libraryDependencies += "com.lihaoyi" %% "cask" % "0.8.2"
libraryDependencies += "com.lihaoyi" %% "pprint" % "0.7.3"

// libraryDependencies += "com.github.xuwei-k" %% "jwt-scala" % "1.7.0"
// usage: https://jwt-scala.github.io/jwt-scala/jwt-circe.html
libraryDependencies += "com.github.jwt-scala" %% "jwt-circe" % "8.0.1"

//libraryDependencies ++= Seq(
//    "net.debasishg" %% "redisclient" % "3.42"
//)


// excludeDependencies ++= Seq(
//   ExclusionRule("com.lihaoyi", "geny_2.13")
// )

Compile / run / mainClass := Some("net.bestqa.caskApp")
dockerBaseImage := "openjdk:jre-alpine"
dockerExposedPorts ++= Seq(9093)
enablePlugins(JavaAppPackaging)
enablePlugins(DockerPlugin)
enablePlugins(AshScriptPlugin)

//scalacOptions += "-language:implicitConversions"
// addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
```
uncomment this lines and the error goes away.

```
// excludeDependencies ++= Seq(
//   ExclusionRule("com.lihaoyi", "geny_2.13")
// )
```

**Comment by lolgab** [comment] 2022-07-08 15:00
Not sure what the problem is, but it is a problem of some other library depending on geny, not of geny itself.
I'm closing this issue since it doesn't belong here.

**Closed by lolgab** 2022-07-08 15:00 UTC
